### ISSUE TITLE
The scrobbler just recognise when in english

### ISSUE THREAD

**Issue by Sfielks** [yungtry/CatalinaScrobbler#1]
I've made some tests in my Mac (it was with brazilian portuguese – my native language) and I noticed that the code just recognize the Apple Music app when it's called "Music" (in portuguese the app name is "Música"). So, until a change, is needed to be using english in the system.
![Screen Shot 2019-07-03 at 06 20 04](https://user-images.githubusercontent.com/17534887/60579986-a2798080-9d5a-11e9-91a5-d6b17ac1f1ca.png)
![image](https://user-images.githubusercontent.com/17534887/60580045-c341d600-9d5a-11e9-8361-329f6ac822b8.png)

**Comment by yungtry** [comment]
Thank you for reporting the bug. I will try to fix it as soon as I get access to the computer with macOS Catalina (most probably tomorrow).

**Comment by Sfielks** [comment]
Unfortunately, I'm very busy this week, but I thought that  using the 'Bundle Identifier' from the Music app ("com.apple.Music") fix part of the issue. I'm not sure, it's just a thought (in the weekend I'll try to test this);
