### ISSUE TITLE
JavaScript error? 

### ISSUE THREAD

**Issue by thewhip302** [yungtry/CatalinaScrobbler#10]
Me again lol, but it appears with the release of 1.0.8 (which is still called 1.0.7 in the files?), a JavaScript error occurs on opening: 

Uncaught Exception:
Error: spawn osascript EAGAIN
    at Process.ChildProcess._handle.onexit (internal/child_process.js:246:19)
    at onErrorNT (internal/child_process.js:429:16)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

This error will continuously pop up until the closure of the app, unsure what process replicates it (though preferences will reproduce the error instantly, whereas it takes around ~5 seconds of the app being open for it to occur on its own)

**Comment by yungtry** [comment]
Literally just woke up to see the exact same error. I do not really know how to fix it as the error message itself doesn't tell anything. From what I read on the Internet and other app's GitHub issues It seems like that error pops up when user has exceeded certain process limit. I think this does happen when your computer goes into sleep mode.

Can you recall what have you been doing before this message popped up?
Do you see anything abnormal when this pops up and you look at your process list in Activity Monitor app?

The only thing I can do for now to sort of "fix" it, is to handle the error but this won't make the app work I guess.

https://github.com/atom/atom/issues/4692#issuecomment-67589308
https://github.com/balena-io/etcher/issues/1578#issuecomment-314129434

**Comment by yungtry** [comment]
I figured out that for some reason it calls osascript too many times and if fills memory causing it to display this message. This may be connected to #3

**Comment by yungtry** [comment]
@thewhip302 Tested it for a few days with no major bugs. Does it work for you? 
https://github.com/yungtry/CatalinaScrobbler/releases/tag/1.0.9
