### ISSUE TITLE
Antivirus disrupts getting data from iTunes

### ISSUE THREAD

**Issue by aileyd** [yungtry/CatalinaScrobbler#14]
I believe that I'm probably just an idiot and that there's probably a simple solution but nothing scrobbles for me and the scrobbler tells me that it is "paused." Have I done something wrong in installing it or is this known to happen?

**Comment by yungtry** [comment]
Need more details. Is it happening with every single song you listen to or is it just one particural song? Are you listening to the song from playlist, album or in another way? Does song's title/album title/artist name contains weird characters such as " \ " ? What version of CatalinaScrobbler are you using? Are scrobbling through Apple Music or iTunes?

**Comment by aileyd** [comment]
It's happening with every single song, nothing scrobbles. I've been listening through iTunes. I've been listening through albums, some through playlists. There's no way to tell whether it's acknowledging that music is being played. When I click on the scrobbler icon on the menu bar, the drop down options are "paused," "preferences" and "quit."

**Comment by yungtry** [comment]
What release does that happen on? Is that 1.1.1 or 1.1.0? Can you recall if the app asked you for permission to control iTunes? Did you change the name of iTunes.app to something different? 

Do you have any basic knowledge on how to use a terminal? That would help in getting a specific error message.

**Comment by aileyd** [comment]
This is on 1.1.1. It didn’t ask me to control iTunes and I haven’t changed the iTunes name, as far as I know it should be named its original name. I could try using 1.1.0?

No knowledge on how to use a terminal, unfortunately.

**Comment by yungtry** [comment]
It means that for some reason the app thinks you're using Apple Music instead of iTunes. Give the older version a try and let me know if it works there.

https://github.com/yungtry/CatalinaScrobbler/releases/tag/1.1.0

**Comment by aileyd** [comment]
The older version didn't ask to control iTunes either and continues not to scrobble. Could it be the way in which I'm installing it? I allowed it to open through security and privacy settings but is there an additional step that I'm missing?

**Comment by yungtry** [comment]
That's weird. And no, there shouldn't be any difference in how you install the app. First of all the app should ask you for permission to control Finder to detect whether you're using Apple Music or iTunes. Had you given the permissions for that?

**Comment by aileyd** [comment]
Yep, it did ask for permission to control Finder and I gave it permission. I'll try deleting it and re-downloading, see if that makes a difference? And then allow it permission to access Finder again. I'll double check and ensure that iTunes is still named iTunes.app as well.

**Comment by aileyd** [comment]
So there isn't an iTunes app, only a music app. Is there a way that I can manually have it detect the music app?

**Comment by yungtry** [comment]
Yup. Right-click on the app, select "Show package contents", Navigate to Contents/Resources/app/lib/applescript. Now you need to edit every file in that folder and change every "com.apple.Music" to "com.apple.iTunes". Not a perfect solution but might work.

**Comment by aileyd** [comment]
I can navigate to Contents/Resources but I can't find app/lib/applescript. Within the Resources folder there is a file that reads "com.apple.Music.sdef" but it can't be renamed.

**Comment by yungtry** [comment]
Hm. That's not possible since the "app" folder contains all of the app's files, therefore it would not run at all if such a folder didn't exist. Do you have any anti-malware protection by any chance or other apps that may modify/delete files? Another possibility is that these files are being omitted while unzipping the app.

**Comment by aileyd** [comment]
I have Trend Micro Antivirus. I tried searching my Mac for "com.apple.Music" and googled a few different ways to find an applescript folder but nothing has come up. At this point I'm kind of stuck.

**Comment by yungtry** [comment]
Your anti-virus is deleting the AppleScript files needed by the app thinking it's going to do something malicious. Try turning it off and re-download the app once again. If it does work with your anti-virus off, then try to find a way to add an exception for CatalinaScrobbler.

**Comment by aileyd** [comment]
I deleted the anti-virus entirely as it was out of date and wasn't working anyway. However, CatalinaScrobbler still isn't working for me. The anti-virus might still have had some type of effect on it? I don't really know but I can't think of any other reason for it to not be working/be blocked.

**Comment by yungtry** [comment]
Go to Security & Privacy->Privacy in your preferences. Click through options and check if it's there. Restarting your mac may help too.
