### ISSUE TITLE
Scrobbling Not Working (Apple Music)

### ISSUE THREAD

**Issue by LeeTranMN** [yungtry/CatalinaScrobbler#17]
Scrobbling from Apple Music isn't working at all for me. I've tried restarting both Apple Music and my computer. I also tried rolling back to 1.1.0 to no avail. 

CatalinaScrobbler Version: 1.1.1
Apple Music Version: 1.0.0.426
macOS Version: 10.15

**Comment by LeeTranMN** [comment]
Update: Cloned the repository and ran the application manually and scrobbling worked

**Comment by yungtry** [comment]
CatalinaScrobbler works by executing Apple Script commands to Apple Music. Antiviruses often block the application thinking it's doing something malicious. Try disabling your antivirus if you use one and then redownload CatalinaScrobbler.

Also macOS doesn't remove iTunes after upgrading to Catalina for some users. Check if there's iTunes in /Applications folder and remove it.

**Comment by LeeTranMN** [comment]
My Antivirus isn't blocking anything and there's no iTunes in my /Applications folder to remove.

Worth noting that when I ran the application manually (both in VSCode and iterm2) it asked for permissions to control Apple Music, but running the pre-built release never asked for that permission.

**Comment by yungtry** [comment]
What antivirus do you use?
Also verify the files:
Right-click the app->Show Package Contents->Navigate to Contents/Resources/app/lib/applescript". There should be four files: "detect.scpt", "loop.scpt", "nowplaying.scpt", "state.scpt". I'm pretty sure your antivirus removes one of them since it's unverified apple script from the Internet. I might be wrong though.

**Comment by LeeTranMN** [comment]
Using Sophos (it's a work computer so I don't have a choice)

All of those files are present.

Also another update to help pinpoint this: If I Right-click app->Show Package-Contents and navigate to Contents/MacOS and drag CatalinaScrobbler to my terminal scrobbling works fine.

**Comment by LeeTranMN** [comment]
I think a more accurate title for this issue is that the pre-built application isn't properly requesting permissions for `Music`

![image](https://user-images.githubusercontent.com/54418451/67023389-5a435b80-f0c8-11e9-9e15-27dd040fb94c.png)

**Comment by LeeTranMN** [comment]
I did a manual build and ran the result, and **that** one asked for permissions to `Music` and scrobbled appropriately. I closed out of that instance and re-opened the original that I downloaded from the resources page and scrobbling was functional as macOS thought they were both the same thing.

**Comment by crescentrose** [comment]
Same issue here, once manually built it scrobbles without issue but the pre-built binary doesn't ask for the Music permission.

**Comment by LeeTranMN** [comment]
Alright I finally managed to recreate the issue locally and I think I _may_ have tracked down the root issue:

The applescripts in the repository all reference `com.apple.Music`, but the scripts in the freshly downloaded package reference `com.apple.iTunes`. After running the downloaded package these scripts don't change, even though they're supposed to.

If I change the scripts in my project to match the ones in the downloaded package and build I get the same issue that happens with the downloaded package.

However, if I change those scripts to reference `com.apple.iTunes` and run in my IDE (without building) those scripts get overwritten.

This leads me to believe there might be an issue with editing the scripts at runtime.

I'm gonna try to code up a fix that just has separate scripts for iTunes and Music and points at the appropriate scripts at runtime depending on what player the user has installed

**Comment by yungtry** [comment]
I've updated the release to the one that have Apple Music set by default. It should work out of the box now. It must have something to do with how permissions are handled in Catalina since it worked on Mojave.

**Comment by yungtry** [comment]
I've just released a new version with fixes made by @leestran1995-daugherty (thanks❤️). Let me know if it works for you guys.
