### ISSUE TITLE
Does it support device scrobbling?

### ISSUE THREAD

**Issue by arvaki** [yungtry/CatalinaScrobbler#19]

**Comment by yungtry** [comment]
What do you exactly mean? If you're asking if it scrobbles songs from other devices (iPhone, iPad, etc.) then no. It works locally relying on files on your computer rather than Apple Music API (because I'm cheap and I cannot afford to buy Apple Developer license 😢).

**Comment by arvaki** [comment]
This is exactly what I’m asking about. Thanks. 

As I understand, the official scrobbler reads ‘.itdb’ files so it relies on files on a computer too. But something went wrong and it scrobbles “now playing” only on Catalina. So I was hoping your project may help.
