### ISSUE TITLE
please support auto-start and auto-login

### ISSUE THREAD

**Issue by kikandychan** [yungtry/CatalinaScrobbler#6]
both of them are basic function for this app. so please

**Comment by yungtry** [comment]
I was waiting for someone to ask for it actually, cause I've doubted that anybody would use my app. As soon as I get more free time I will add it in the next update.

**Comment by yungtry** [comment]
The app has been updated to add these functionalities.

https://github.com/yungtry/CatalinaScrobbler/releases
