### ISSUE TITLE
Scrobbling no longer recording as of latest update 

### ISSUE THREAD

**Issue by thewhip302** [yungtry/CatalinaScrobbler#9]
<img width="123" alt="Screenshot at Jul 29 08-52-28" src="https://user-images.githubusercontent.com/53394665/62015443-416c8d80-b1de-11e9-926c-c1e44056d99f.png">

When playing music, this is the only screen; no data is actually being sent to last.fm, this problem occurs even after restarting music and the scrobbler. Maybe one of the additions in the past 2 updates caused an issue? 1.0.5 was the last update I was able to reproduce a connection to last.fm

**Comment by yungtry** [comment]
Did the app ask you for permission to control Apple Music?

**Comment by thewhip302** [comment]
No; I can't reproduce that pop-up on either 1.0.6 or 1.0.7, but it comes up with 1.0.5; CatalinaScrobbler only asks for access to Finder and System Preferences (for opening on startup) on newer versions

**Comment by yungtry** [comment]
I've updated the app and release. Let me know if it works now. https://github.com/yungtry/CatalinaScrobbler/releases/tag/1.0.8

**Comment by thewhip302** [comment]
Yes, that seemed to have fixed the issue, thank you

**Comment by Tom34772** [comment]
I am having the same problem also - I put in my credentials for last.fm and nothing is scrobbling. (I checked the website.)

The Catalina Scrobbler interface says, "Paused" and never updates...

-- Tom

**Comment by yungtry** [comment]
@Tom34772 Does it happen with all songs?

I'm almost certain It's caused by apostrophe in song data (artist, track or album). Almost the same thing as #5. I will push the fix in the following days.

**Comment by 2dioxyde** [comment]
@yungtry Same problem with all songs

**Comment by yungtry** [comment]
@2dioxyde Could you provide more details in #17? Thank you.

**Comment by 2dioxyde** [comment]
I did everything step by step exactly as it was told in the "automatic" section of readme. I've launched the music app and faced the "Paused" button. I tried restarting the music app, restarting the system and the music app, playing and stopping different tracks, then I installed the previous version of the scrobbler and nothing has changed

**Comment by LeeTranMN** [comment]
@2dioxyde For a stopgap measure to make scrobbling work while a fix is worked on:

Right-click the app->Show Package Contents->Navigate to Contents/MacOS

Open a terminal window and click and drag `CatalinaScrobbler` onto it, then press enter and click "OK" to the three permissions popups that should popup.
